### ISSUE TITLE
header-only configure gives 'src/mcmc_algos.cpp' missing error

### ISSUE THREAD

**Issue by MarcToussaint** [kthohr/mcmc#10]
When trying to install the header-only version, I get this error:

> mtoussai@riley2:~/git/mcmc> ./configure --header-only-version
sed: can't read /home/mtoussai/git/mcmc/src/mcmc_algos.cpp: No such file or directory

**Comment by kthohr** [comment]
Oops. Should be fixed now. Thanks for flagging.

**Comment by skiptoniam** [comment]
I had this same issue too, thanks for fixing
