### ISSUE TITLE
GPL too strict.

### ISSUE THREAD

**Issue by acdemiralp** [kthohr/mcmc#2]
Hello, 

I have been inspired by your approach to the MCMC samplers. However the GPL license prevents me from utilizing the library or parts of it in any other library/application which has a freer license than GPL such as MIT or BSD. I just wanted to ask if this is intentional or whether you would be okay with a freer license.

**Comment by kthohr** [comment]
Greetings!

No great philosophical reasons for the license, mostly due to default bias when I started. I'm in the process of moving some projects to Apache, Version 2.0; the same will happen to this library. I'd just like to add a few more tests first. Should happen in the next week or so...

**Comment by kthohr** [comment]
The license is now Apache Version 2.
