### ISSUE TITLE
row vs column vector dimension mismatch in de

### ISSUE THREAD

**Issue by Maginor** [kthohr/mcmc#3]
Line 136 in de.cpp causes arma to throw a dimension mismatch exception (at least if n_vals is more than 1).
The bug is fixed if I change line 134 to
arma::rowvec prop_rand = arma::randu(1, n_vals)*(2*par_b) - par_b; // generate a vector of U[-b,b] RVs

**Comment by kthohr** [comment]
Thanks for reporting this (and sorry for the delay). Should be fixed now.
